name: Salesforce CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Salesforce CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with Salesforce Dev
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile ./server.key --username ${{ secrets.DEV_USERNAME }} --instanceurl https://test.salesforce.com

      - name: Deploy code to Salesforce Dev
        run: sfdx force:source:deploy -p force-app -u ${{ secrets.DEV_USERNAME }}

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Setup Salesforce CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with Salesforce QA
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile ./server.key --username ${{ secrets.QA_USERNAME }} --instanceurl https://test.salesforce.com

      - name: Deploy code to Salesforce QA
        run: sfdx force:source:deploy -p force-app -u ${{ secrets.QA_USERNAME }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-qa
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Setup Salesforce CLI
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Salesforce CLI
        run: npm install -g sfdx-cli

      - name: Authenticate with Salesforce Prod
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.SALESFORCE_CLIENT_ID }} --jwtkeyfile ./server.key --username ${{ secrets.PROD_USERNAME }} --instanceurl https://login.salesforce.com

      - name: Deploy code to Salesforce Prod
        run: sfdx force:source:deploy -p force-app -u ${{ secrets.PROD_USERNAME }}
